fastjsonschema/generator.py

Just so both `2018-04-25T17:20:00.000Z` and `2018-04-25T17:20:00.000+00:00` are ok :) plus avoid impossible datetimes like `2018-99-99T99:99:99`.

More precise date-time regex and handling of '+hh:mm'

---

fastjsonschema/draft04.py
tests/test_datetime.py

Added a test case that fails with the old regex and is green with the new regex.

Allow date-time strings without milliseconds. Fixes #23

---

fastjsonschema/generator.py
tests/test_compile_to_code.py

In code generation, long patterns were cut off, because it used the string representation of the compiled pattern object. With this PR it uses the actual string in the pattern attribute. Also added a test case that was red before and is green after.

Don't use str() result of compiled patterns (because it cuts off string). Fixes #22

---

fastjsonschema/__init__.py
fastjsonschema/draft04.py
pylintrc
tox.ini

Added py37 to tox environment list.
It finds an error with my previous PR:
The docs show a change in `Pattern.sub`.
```
Changed in version 3.7: Unknown escapes in repl consisting of '\' and an ASCII letter now are errors.
```
```
>>> import re
>>> DOLLAR_FINDER = re.compile(r"(?<!\\)\$")
>>> DOLLAR_FINDER.sub(r'\Z', 'hello$')
Traceback (most recent call last):
File "/usr/local/lib/python3.7/sre_parse.py", line 1021, in parse_template
this = chr(ESCAPES[this][1])
KeyError: '\\Z'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.7/re.py", line 309, in _subx
template = _compile_repl(template, pattern)
File "/usr/local/lib/python3.7/re.py", line 300, in _compile_repl
return …
```

Python 3.7 regex bug fixed

---

fastjsonschema/ref_resolver.py
setup.py
tests/json_schema/utils.py

Now memory usage is much smaller ( 7 Mb instead of 15 Mb ).
```markdown
Line #    Mem usage    Increment   Line Contents
================================================
6     10.5 MiB     10.5 MiB   @profile
7                             def main():
8     17.5 MiB      7.0 MiB       import fastjsonschema
9                             
10                                 schema = {
11                                     'properties':
12                                         {
13     17.5 MiB      0.0 MiB                   'hey': {}
14                                         },
15                                     'required': [
16     17.5 MiB      0.0 MiB               'hey'
17                                     ],
18     17.5 MiB      0.0 MiB           'type': 'object'
19 …
```

Substituted requests package with urllib

---

Makefile
fastjsonschema/draft04.py
tests/test_pattern_properties.py
tests/test_string.py

This is a fix for #50. It consists of 3 steps:
1. Make `pytest` run with `-W default` so that warnings that are [hidden by default](https://docs.python.org/3/library/warnings.html#default-warning-filter) (such as `DeprecationWarning`) get visible.
2. Add escaping in exception message for `pattern`. Here, incorrect escaping didn’t affect matching itself.
2. Add escaping in generated code for `patternProperties`. Here, incorrect escaping **did affect matching itself.**
I added tests for the fixes. I wasn't very clear about the structure of the test suite, so I added them at places that seemed most appropriate. Let me know if I should move them elsewhere or change them in any way.

Fix escaping for “pattern” and “patternProperties”

---

fastjsonschema/__init__.py
fastjsonschema/draft04.py
fastjsonschema/draft06.py
fastjsonschema/draft07.py
fastjsonschema/generator.py
tests/conftest.py
tests/test_format.py

Hello,
We would like to contribute in this project by adding the format_checkers feature that consists to allow custom format to be check during the `compile` method execution. 
The format_checkers is optional and only available for `compile`.
A fellow, @gpakosz, already contact you about this.
Thanks

Add handlers to validate methode and introduce format_checkers

---

fastjsonschema/__init__.py

This minor change to the `validate` documentation will make the example execute as written.

Minor correction to validate documentation

---

performance.py

`jsonschema` can be compiled as well, added test case  
Also, some PEP8 improvements in performance script, plus there's no need to create `temp` folder
test run example
```
$ make performance
Number: 1000
fast_compiled        valid      ==>  0.0464646
fast_compiled        invalid    ==>  0.0030227
fast_file            valid      ==>  0.0461219
fast_file            invalid    ==>  0.0030608
fast_not_compiled    valid      ==> 11.4627202
fast_not_compiled    invalid    ==>  2.5726230
jsonschema           valid      ==>  7.5844927
jsonschema           invalid    ==>  1.9204665
jsonschema_compiled  valid      ==>  0.6938364
jsonschema_compiled  invalid    ==>  0.0359244
jsonspec             valid      ==>  9.0715843
jsonspec             invalid    ==>  2.1650488
validictory          valid …
```

fair performance test + robust script

---

fastjsonschema/draft04.py
tests/test_object.py

see spec https://swagger.io/docs/specification/data-models/dictionaries/

additionalProperties == {} equivalent to True

---

fastjsonschema/__init__.py
fastjsonschema/generator.py
tests/test_compile_to_code.py

Previously `custom_formats` was assumed to be global, which works fine for evaluation, but results in errors when using generated code.
This PR should fix #128.
The approach used was to add a second argument to the `validate` function.
For execution, the function is wrapped with a `partial` that hides the extra argument (and therefore avoids changes in the API or documentation).

Add `custom_formats` argument to generated code

---

fastjsonschema/draft04.py
tests/conftest.py
tests/test_array.py

closes #107 
this is not the ugly version of the function
```python
def fn2(var):
if isinstance(var, (dict, list)):
if hasattr(var, "items"):
return frozenset(dict((k, fn(v)) for k, v in var.items()).items())
return tuple(fn(v) for v in var)
elif isinstance(var, bool):
return str(var)  # because of '1' and 'True' are equal
return var
```

resolving uniqueItems is stable now

---

fastjsonschema/__init__.py
fastjsonschema/generator.py
fastjsonschema/ref_resolver.py
tests/test_integration.py

This PR is an attempt to fix #129.
The approach adopted here was to replace all the empty dictionaries used as mutable default arguments with `None` and use the handy `self.value = value or {}` expression to make sure we have an empty default dictionary...

Fix unexpected caching (issue #129)

---

fastjsonschema/exceptions.py
fastjsonschema/generator.py
tests/test_compile_to_code.py
tests/test_object.py

This is just a "rebased" version of https://github.com/horejsek/python-fastjsonschema/pull/92, that can be compared and rebased into master.
I think this approach is really useful when debugging errors. More than once I found myself trying to understand which property exactly was failing. Preserving the complete path make is less confusing and more straight forward to find the errors.
All the work was done by @ZbigniewRA in #92.
Potentially, this closes #63.

Preserving full path to a value when following $ref

---

fastjsonschema/generator.py
tests/conftest.py
tests/examples/conditional/address.schema.json
tests/examples/conditional/invalid.error
tests/examples/conditional/invalid.json
tests/examples/conditional/valid.json
tests/test_composition.py

This change should fix #141.
By expanding any `$ref` field in the schema definition that is available in the `JsonSchemaValueException` objects, we make it easier for the API consumers to provide more meaningful errors.

Expand `$ref` when assigning the `definition` field to `JsonSchemaValueException`

---

fastjsonschema/draft04.py
fastjsonschema/generator.py
tests/test_array.py

Fix #114.
In #114, the faulty schema does not provide any validation the array items, despite of explicitly having "items" as a non-empty dict.
This results in a generated empty for-loop, which in turn will result in an `IndentationError` when evaluated by Python.
In this PR, I propose to fill the empty for-loop with a `pass` statement.

Prevent items generator to create an empty for-loop (issue 114)

---

fastjsonschema/draft04.py
fastjsonschema/generator.py
tests/test_common.py
tests/test_integration.py

In https://github.com/horejsek/python-fastjsonschema/pull/142#issuecomment-1050814835 I asked if the author would be interested in some error message improvements, so I experimented a bit with making some changes to the errors.
My original idea was to use the definition to generate a little summary of what is expected. However that would add a lot of complexity, and I don't think that is a good approach... So instead I tried to improve 2 of them (very slightly).
Currently, the error messages of `oneOf`, `anyOf` and `not` (when analysed without the definition JSON) don't read so well. For example:
```
data must be valid exactly by one of oneOf definition
data must be valid by one of anyOf definition
data must not be valid by not definition
```
In this PR I am proposing changing a little …

Improve error message for `oneOf`, `anyOf` and `not` (slightly)

---

setup.py
tox.ini

Looking at the github workflows that are defined it seems like python 3.9 and 3.10 are supported but just not listed in the setup.py metadata
https://github.com/horejsek/python-fastjsonschema/blob/1aad747bab39d4b1201ab99917463f4079955ecd/.github/workflows/tests.yml#L18

Update python support metadata

---

fastjsonschema/draft04.py
fastjsonschema/draft06.py
fastjsonschema/generator.py
tests/test_number.py

Hello, I've added support for Decimal in `number` fields
Closes https://github.com/horejsek/python-fastjsonschema/issues/122

Add support for `decimal.Decimal` as number

---

fastjsonschema/draft04.py
tests/test_integration.py
tests/test_object.py

only include _missing properties in the error message for required props
```
>>> fastjsonschema.validate({'required': ['foo', 'bar']}, {'foo': 1})
```
before:
```
JsonSchemaValueException: data must contain ['foo', 'bar'] properties
```
after:
```
JsonSchemaValueException: data must contain ['bar'] properties
```
fixes #175

improve error message for missing required props

---

fastjsonschema/ref_resolver.py

Zdravím. :wave: 
First of all thanks for the great project! I am currently thinking about migrating our Python CLI app from `jsonschema`.
The main issue for us is not really the validation speed, but rather the import speed, since we're reading and validating a single config file at each app invocation.
`fastjsonschema` import time is already great (whooping 60ms faster than `jsonschema`), 
but this little change improves speed by another ~30ms, from 77ms to 45ms with Python 3.10 on my machine.

Lazy import urllib

---

.github/workflows/tests.yml
setup.py
tox.ini

The package seems to work with Python 3.12, so this just _declares_ support for it and runs tests on it in CI.

Test on Python 3.12

---

tests/test_pattern_properties.py
tests/test_string.py

> To ensure that no warnings are emitted, use:
> ```python
> with warnings.catch_warnings():
>     warnings.simplefilter("error")
>     ...
> ```
https://docs.pytest.org/en/7.0.x/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests

Use `warnings.catch_warnings` instead of `pytest.warns(None)` in tests

---

.github/workflows/tests.yml
setup.py
tox.ini

Python 3.13 was released on 2024-10-07. This package already supports it, so this only adds the packaging metadata and adds it to the test matrix to prevent regressions.

Test on Python 3.13

---

fastjsonschema/draft07.py
tests/test_format.py

Version 2.21.0 introduced a bug causing all strings with format date to fail if the date is in October. This PR fixes the changed regular expression.

Fix date pattern regexp
